# include:
#   - path: ./airflow.yml

services:
  postgres:
    image: postgres:13
    container_name: daily-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_CONN_DAILY_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_CONN_DAILY_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CONN_DAILY_DB}
    ports:
      - "${POSTGRES_CONN_DAILY_PORT}:5432"   # host 5435 -> Postgres's internal port 5432
    volumes:
    # If start with ( ./ = bind mount, it will read data on the local pc )( [name] = the docker will handle the data automatically )
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/empty-db-startup.sql:/docker-entrypoint-initdb.d/empty-db-startup.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_CONN_DAILY_USERNAME}", "-d", "${POSTGRES_CONN_DAILY_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres-data:
