#!/usr/bin/env python3
#
# Copyright (C) 2026 
#			Written by 
#
########################################################
#
#	STANDARD IMPORTS
#

from fastapi import FastAPI, HTTPException

import psycopg2

import os

from dotenv import load_dotenv

from pathlib import Path

import logging

from pydantic import BaseModel

########################################################
#
#	LOCAL IMPORTS
#



########################################################
#
#	GLOBALS
#

BASE_DIR = Path(__file__).resolve().parents[2]
ENV_PATH = BASE_DIR / ".env"

logger = logging.getLogger(__name__)

TABLE_NAME = "orders"

SCHEMA_NAME = "public"

app = FastAPI()

########################################################
#
#	HELPER FUNCTIONS
#

load_dotenv( dotenv_path = ENV_PATH )

def get_conn_cursor():
    # The error will appear when use the "" with "" on python 3.10, f-string only use the "" to recieve the string inside, so If you want to select the valiable need to use the '' instead.
    required = [ "POSTGRES_CONN_DAILY_DB", "POSTGRES_CONN_DAILY_USERNAME", "POSTGRES_CONN_DAILY_PASSWORD", "POSTGRES_CONN_DAILY_PORT" ]
    missing = [ name for name in required if not os.getenv(name) ]
    if missing:
        raise RuntimeError( f"Missing environment variables: {', '.join(missing)}" )

    conn = psycopg2.connect(
        host=os.getenv('DB_HOST', 'localhost'),            # <- This variable will change if It call from contianer in docker( relate to service name in docker-compose.yml )
        dbname=os.getenv('POSTGRES_CONN_DAILY_DB'),
        user=os.getenv('POSTGRES_CONN_DAILY_USERNAME'),
        password=os.getenv('POSTGRES_CONN_DAILY_PASSWORD'),
        port=os.getenv('POSTGRES_CONN_DAILY_PORT')
    )
    cur = conn.cursor()
    return conn, cur


def close_conn_cursor(conn, cur):
    cur.close()
    conn.close()

def convertIntoJson( column, output ):
    '''
    Parameters
    -------
    column: list
        The column of the postgres database ['order_id', 'table_id', 'menu', 'cost']

    output: tuple
        The value of all rows in the postgres database [(1, 1, "Hambuger", 500), (2, 2, "sausage", 100), (3, 1, "Water", 50)]

    Returns
    -------
    json_str: json type
        The output in form of json file
    '''  

    data = []
    for eachRow in output:
        data.append(dict(zip(column, eachRow)))
   
    return data

########################################################
#
#	CLASS DEFINITIONS
#

class OrderCreate( BaseModel ):
    table_id : int
    menu : str
    cost : float

########################################################
#
#   MAIN DEFINITIONS
#

# # 1. Select all the order which was "x" table.
@app.get( "/restaurant/getOrders/{numTable}" )
def getOrderOnTable( numTable : int ):
    conn, cur = None, None
    try:
        conn, cur = get_conn_cursor()

        select_sql = f'''
        SELECT *
        FROM {SCHEMA_NAME}.{TABLE_NAME}
        WHERE table_id = %s;
        '''

        cur.execute(select_sql, ( numTable, ))
        output = cur.fetchall()
        columns = [ desc[0] for desc in cur.description ]

        logger.info( f"Select all the information from the database" )

        result = convertIntoJson( columns, output )
        return result

        ## If you want to get in form of json you can comment "return result" and uncomment below 2 rows.
        # json_str = json.dumps( result )
        # return json_str
        
    except Exception as e:
        logger.error(f"An error occurred during the Select on table: {numTable} of {SCHEMA_NAME}:{TABLE_NAME} raise {e}")
        raise HTTPException( status_code=500, detail="Internal database error" )
    
    finally:
        if conn and cur:
            close_conn_cursor( conn, cur )

# 2. Select all the order which all table.
@app.get( "/restaurant/getOrders" )
def getAllOrder():
    conn, cur = None, None
    try:
        conn, cur = get_conn_cursor()

        select_sql = f'''
        SELECT *
        FROM {SCHEMA_NAME}.{TABLE_NAME};
        '''

        cur.execute(select_sql)
        output = cur.fetchall()
        columns = [ desc[0] for desc in cur.description ]

        logger.info( f"Select all the information from the database" )

        result = convertIntoJson( columns, output )
        return result

        ## If you want to get in form of json you can comment "return result" and uncomment below 2 rows.
        # json_str = json.dumps( result )
        # return json_str

    except Exception as e:
        logger.error(f"An error occurred during the Select all of {SCHEMA_NAME}:{TABLE_NAME} raise {e}")
        raise HTTPException( status_code=500, detail="Internal database error" )
    
    finally:
        if conn and cur:
            close_conn_cursor( conn, cur )

# 3. Add the order in database.
@app.post( "/restaurant/insertOrder" )
def insertOrderDatabase( orderUser : OrderCreate ):
    conn, cur = None, None
    try:
        conn, cur = get_conn_cursor()

        # order_id is generated by the database ( identity column )
        insert_sql = f'''
        INSERT INTO {SCHEMA_NAME}.{TABLE_NAME} ( table_id, menu, cost )
        VALUES ( %s, %s, %s );
        '''

        cur.execute( insert_sql, ( orderUser.table_id, orderUser.menu, orderUser.cost ) )
        conn.commit()

        logger.info( f"Insert the order into the database correctly" )

        return { "Message": f"complete insert the order into database" }

    except Exception as e:
        logger.error( f"An error occurred during the insert orders in {SCHEMA_NAME}:{TABLE_NAME} raise {e}" )
        raise HTTPException( status_code=500, detail="Internal database error" )
    
    finally:
        if conn and cur:
            close_conn_cursor( conn, cur )

# 4. Delete the order which was using the order_id.
@app.delete( "/restaurant/delOrders/orderId/{idOrder}" )
def deleteOrderId( idOrder : int ):
    conn, cur = None, None
    try:
        conn, cur = get_conn_cursor()

        delete_sql = f'''
        DELETE FROM {SCHEMA_NAME}.{TABLE_NAME}
        WHERE order_id = %s;
        '''

        cur.execute( delete_sql, ( idOrder, ) )
        conn.commit()

        logger.info( f"Delelt the orderId from the database which was id = { idOrder }" )

        return { "Message": f"complete delete order : {idOrder}" }

    except Exception as e:
        logger.error(f"An error occurred during the delete some of {SCHEMA_NAME}:{TABLE_NAME} raise {e}")
        raise HTTPException( status_code=500, detail="Internal database error" )
        
    finally:
        if conn and cur:
            close_conn_cursor( conn, cur )

# 5. Delete the order on the table.
@app.delete( "/restaurant/delOrders/tableId/{idTable}" )
def deleteTableId( idTable : int ):
    conn, cur = None, None
    try:
        conn, cur = get_conn_cursor()

        delete_sql = f'''
        DELETE FROM {SCHEMA_NAME}.{TABLE_NAME}
        WHERE table_id = %s;
        '''

        cur.execute( delete_sql, ( idTable, ) )
        conn.commit()

        logger.info( f"Delte all the orders in the tableId from the database which was table = {idTable}" )

        return { "Message": f"complete delete all orders in tabel : {idTable}" }

    except Exception as e:
        logger.error(f"An error occurred during the delete all of {SCHEMA_NAME}:{TABLE_NAME} raise {e}")
        raise HTTPException( status_code=500, detail="Internal database error" )

    finally:
        if conn and cur:
            close_conn_cursor( conn, cur )
